#include "espclaw/admin_ui.h"

#include <string.h>

static const char *ESPCLAW_ADMIN_UI =
    "<!doctype html>\n"
    "<html lang='en'>\n"
    "<head>\n"
    "  <meta charset='utf-8'>\n"
    "  <meta name='viewport' content='width=device-width,initial-scale=1'>\n"
    "  <title>ESPClaw Admin</title>\n"
    "  <style>\n"
    "    :root{color-scheme:light;--bg:#f3efe6;--panel:#fffdf8;--panel-2:#f8f4ec;--line:#ddd3c3;--ink:#163239;--muted:#617278;--accent:#173b43;--accent-2:#b8d5d0;--ok:#2f6f44;--warn:#916c1f;--danger:#8d3d32;--bubble-user:#eef4f5;--bubble-assistant:#fff7e8;--bubble-tool:#f4efe8;--shadow:0 20px 44px rgba(22,50,57,.08);font-family:'Avenir Next','IBM Plex Sans',system-ui,sans-serif;}\n"
    "    *{box-sizing:border-box;}\n"
    "    body{margin:0;background:radial-gradient(circle at top left,#f9f5ec 0,#f3efe6 45%,#efe7da 100%);color:var(--ink);}\n"
    "    button,input,select,textarea{font:inherit;}\n"
    "    .hero{padding:28px 24px 20px;background:linear-gradient(135deg,#133941 0,#1f4952 45%,#2a5c61 100%);color:#fff9ef;position:sticky;top:0;z-index:10;box-shadow:0 10px 28px rgba(19,57,65,.24);}\n"
    "    .hero-top{display:flex;justify-content:space-between;gap:16px;align-items:flex-start;flex-wrap:wrap;}\n"
    "    .brand h1{margin:0;font-size:2.1rem;letter-spacing:-.04em;}\n"
    "    .brand p{margin:8px 0 0;color:rgba(255,249,239,.78);max-width:60ch;}\n"
    "    .hero-meta,.quick-pills,.chip-row{display:flex;gap:8px;flex-wrap:wrap;}\n"
    "    .pill,.chip{display:inline-flex;align-items:center;gap:6px;padding:8px 12px;border-radius:999px;font-size:.92rem;border:1px solid rgba(255,255,255,.18);background:rgba(255,255,255,.08);backdrop-filter:blur(6px);}\n"
    "    .pill strong,.chip strong{font-weight:700;}\n"
    "    .layout{display:grid;grid-template-columns:minmax(340px,1.3fr) minmax(320px,.95fr);gap:18px;padding:18px;align-items:start;}\n"
    "    .card{background:var(--panel);border:1px solid rgba(221,211,195,.95);border-radius:22px;box-shadow:var(--shadow);}\n"
    "    .chat-shell{padding:18px;display:grid;gap:14px;min-height:calc(100vh - 160px);}\n"
    "    .section-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start;flex-wrap:wrap;}\n"
    "    .section-head h2{margin:0;font-size:1.35rem;letter-spacing:-.03em;}\n"
    "    .section-head p{margin:6px 0 0;color:var(--muted);}\n"
    "    .mini-actions{display:flex;gap:10px;align-items:center;flex-wrap:wrap;}\n"
    "    .mini-actions input{width:170px;}\n"
    "    .chat-transcript{min-height:420px;max-height:62vh;overflow:auto;padding:10px;border:1px solid var(--line);border-radius:18px;background:linear-gradient(180deg,#fffdf8 0,#f6f0e6 100%);display:grid;gap:10px;}\n"
    "    .bubble{max-width:88%;padding:12px 14px;border-radius:18px;border:1px solid rgba(22,50,57,.08);box-shadow:0 8px 20px rgba(22,50,57,.05);}\n"
    "    .bubble .role{font-size:.76rem;text-transform:uppercase;letter-spacing:.08em;color:var(--muted);margin-bottom:6px;}\n"
    "    .bubble.user{margin-left:auto;background:var(--bubble-user);border-bottom-right-radius:6px;}\n"
    "    .bubble.assistant{background:var(--bubble-assistant);border-bottom-left-radius:6px;}\n"
    "    .bubble.tool{background:var(--bubble-tool);border-style:dashed;max-width:100%;}\n"
    "    .bubble pre{margin:0;white-space:pre-wrap;word-break:break-word;font-family:'IBM Plex Mono','SFMono-Regular',monospace;font-size:.9rem;}\n"
    "    .empty-state{display:grid;place-items:center;min-height:220px;text-align:center;color:var(--muted);padding:24px;border:1px dashed var(--line);border-radius:18px;background:rgba(255,255,255,.5);}\n"
    "    .composer{display:grid;gap:10px;}\n"
    "    .composer textarea,.editor textarea,.auth-grid textarea,.advanced textarea{width:100%;min-height:120px;padding:14px 16px;border-radius:18px;border:1px solid var(--line);background:var(--panel-2);resize:vertical;}\n"
    "    .row{display:flex;gap:10px;flex-wrap:wrap;align-items:center;}\n"
    "    .row > *{flex:1 1 0;}\n"
    "    .row.compact > *{flex:0 1 auto;}\n"
    "    button{appearance:none;border:0;border-radius:16px;padding:12px 16px;background:var(--accent);color:#fff9ef;font-weight:700;letter-spacing:-.01em;cursor:pointer;box-shadow:0 8px 18px rgba(23,59,67,.16);}\n"
    "    button.secondary{background:#e9f0ef;color:var(--ink);box-shadow:none;border:1px solid rgba(22,50,57,.08);}\n"
    "    button.ghost{background:transparent;color:var(--ink);box-shadow:none;border:1px solid var(--line);}\n"
    "    button.danger{background:var(--danger);}\n"
    "    input,select{width:100%;padding:12px 14px;border-radius:14px;border:1px solid var(--line);background:#fff;min-height:46px;}\n"
    "    label{display:grid;gap:6px;font-size:.93rem;color:var(--muted);}\n"
    "    .notice{padding:12px 14px;border-radius:16px;background:#eef4ef;border:1px solid #d4e3d4;color:#244231;}\n"
    "    .notice.warn{background:#fff5dd;border-color:#ead29d;color:#704d0e;}\n"
    "    .notice.muted{background:var(--panel-2);border-color:var(--line);color:var(--muted);}\n"
    "    .control-stack{display:grid;gap:16px;}\n"
    "    .nav{display:flex;gap:8px;flex-wrap:wrap;margin-top:14px;}\n"
    "    .nav button{padding:10px 14px;border-radius:999px;}\n"
    "    .nav button.active{background:#fff9ef;color:var(--accent);}\n"
    "    .screen{display:none;}\n"
    "    .screen.active{display:grid;gap:16px;}\n"
    "    .panel{padding:16px;}\n"
    "    .panel h3{margin:0 0 12px;font-size:1.02rem;letter-spacing:-.02em;}\n"
    "    .stats{display:grid;grid-template-columns:repeat(auto-fit,minmax(120px,1fr));gap:10px;}\n"
    "    .stat{padding:12px;border-radius:16px;background:var(--panel-2);border:1px solid var(--line);}\n"
    "    .stat .label{font-size:.82rem;color:var(--muted);}\n"
    "    .stat .value{margin-top:4px;font-weight:800;font-size:1.05rem;letter-spacing:-.03em;}\n"
    "    .mini-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(140px,1fr));gap:10px;}\n"
    "    .mini-card{padding:14px;border-radius:18px;background:linear-gradient(180deg,#fffefc 0,#f6f1e7 100%);border:1px solid var(--line);display:grid;gap:8px;}\n"
    "    .mini-card .title{font-size:.8rem;text-transform:uppercase;letter-spacing:.08em;color:var(--muted);}\n"
    "    .mini-card .big{font-size:1.05rem;font-weight:800;letter-spacing:-.03em;}\n"
    "    .mini-card .sub{font-size:.9rem;color:var(--muted);}\n"
    "    details.module{padding:0;overflow:hidden;}\n"
    "    details.module summary{list-style:none;cursor:pointer;padding:16px 18px;font-weight:800;display:flex;justify-content:space-between;align-items:center;letter-spacing:-.02em;}\n"
    "    details.module summary::-webkit-details-marker{display:none;}\n"
    "    details.module[open] summary{border-bottom:1px solid var(--line);background:rgba(23,59,67,.03);}\n"
    "    .module-body{padding:16px 18px;display:grid;gap:16px;}\n"
    "    .grid-2{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:14px;}\n"
    "    .list{display:grid;gap:10px;}\n"
    "    .list-card{padding:12px 14px;border-radius:16px;border:1px solid var(--line);background:#fff;display:grid;gap:8px;}\n"
    "    .list-card button{width:auto;justify-self:start;}\n"
    "    .tool-list .list-card,.workspace-list .list-card{gap:4px;}\n"
    "    .ok{color:var(--ok);font-weight:700;}\n"
    "    .bad{color:var(--danger);font-weight:700;}\n"
    "    .bars{display:grid;gap:10px;}\n"
    "    .bar-row{display:grid;gap:6px;}\n"
    "    .bar-track{height:10px;border-radius:999px;background:#e7ddd0;overflow:hidden;}\n"
    "    .bar-fill{height:100%;background:linear-gradient(90deg,#6aa39a 0,#20484e 100%);border-radius:999px;}\n"
    "    .advanced{display:grid;gap:10px;padding:12px;border-radius:16px;background:var(--panel-2);border:1px solid var(--line);}\n"
    "    .advanced summary{cursor:pointer;font-weight:700;color:var(--ink);}\n"
    "    .muted{color:var(--muted);}\n"
    "    .sr-only{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap;border:0;}\n"
    "    @media (max-width:980px){.layout{grid-template-columns:1fr;}.chat-shell{min-height:auto;}.chat-transcript{max-height:48vh;}}\n"
    "  </style>\n"
    "</head>\n"
    "<body>\n"
    "  <header class='hero'>\n"
    "    <div class='hero-top'>\n"
    "      <div class='brand'>\n"
    "        <h1>ESPClaw Admin</h1>\n"
    "        <p>Chat-first operator console for onboarding, hardware control, dynamic Lua apps, and local AI-assisted workflows.</p>\n"
    "      </div>\n"
    "      <div id='hero-meta' class='hero-meta'><span class='pill'>Connecting…</span></div>\n"
    "    </div>\n"
    "    <div class='nav'>\n"
    "      <button type='button' class='active' data-screen-target='chat'>Chat</button>\n"
    "      <button type='button' data-screen-target='setup'>Setup</button>\n"
    "      <button type='button' data-screen-target='apps'>Apps</button>\n"
    "      <button type='button' data-screen-target='advanced'>Advanced</button>\n"
    "    </div>\n"
    "  </header>\n"
    "  <main class='layout'>\n"
    "    <section class='card chat-shell'>\n"
    "      <div class='section-head'>\n"
    "        <div>\n"
    "          <h2>Operator Chat</h2>\n"
    "          <p>This is the same slash-command and LLM console exposed on UART0. Use /help for static commands, or ask normally for a model turn.</p>\n"
    "        </div>\n"
    "        <div class='mini-actions'>\n"
    "          <label class='sr-only' for='chat-session-id'>Session</label>\n"
    "          <input id='chat-session-id' autocomplete='off' value='admin' placeholder='session id'>\n"
    "          <button id='load-session' type='button' class='secondary'>Refresh</button>\n"
    "        </div>\n"
    "      </div>\n"
    "      <div id='chat-transcript' class='chat-transcript'><div class='empty-state'>Transcript loads when the chat screen opens.</div></div>\n"
    "      <div class='composer'>\n"
    "        <label for='chat-input' class='sr-only'>Message</label>\n"
    "        <textarea id='chat-input' placeholder='Try /help, /wifi scan, /tool system.info {}, or ask the device to solve a task.'></textarea>\n"
    "        <div class='row compact'>\n"
    "          <label class='chip'><input id='chat-yolo' type='checkbox' style='width:auto;min-height:auto;'> YOLO mode</label>\n"
    "          <button id='run-chat' type='button'>Send To Model</button>\n"
    "          <button id='clear-chat-draft' type='button' class='ghost'>Clear Draft</button>\n"
    "        </div>\n"
    "      </div>\n"
    "      <div id='chat-result' class='notice muted'>Slash commands and model replies will appear here.</div>\n"
    "    </section>\n"
    "    <aside class='control-stack'>\n"
    "      <section class='card panel'>\n"
    "        <h2>Quick Setup</h2>\n"
    "        <div class='mini-grid'>\n"
    "          <div id='provider-summary' class='mini-card'><div class='title'>Provider</div><div class='big'>Not loaded</div><div class='sub'>Open Setup or Advanced.</div></div>\n"
    "          <div id='network-summary' class='mini-card'><div class='title'>Network</div><div class='big'>Not loaded</div><div class='sub'>Open Setup.</div></div>\n"
    "          <div id='board-summary' class='mini-card'><div class='title'>Board</div><div class='big'>Not loaded</div><div class='sub'>Open Setup.</div></div>\n"
    "          <div id='app-summary' class='mini-card'><div class='title'>Apps</div><div class='big'>Not loaded</div><div class='sub'>Open Apps.</div></div>\n"
    "        </div>\n"
    "      </section>\n"
    "      <div id='screen-setup' class='screen'>\n"
    "        <details class='card module' data-load-section='connectivity'>\n"
    "          <summary><span>Connectivity</span><span class='muted'>Wi-Fi and provider auth</span></summary>\n"
    "          <div class='module-body'>\n"
    "            <div class='grid-2'>\n"
    "              <div class='list-card'>\n"
    "                <h3>Network</h3>\n"
    "                <label>Wi-Fi SSID<input id='network-ssid' autocomplete='off' placeholder='Choose from scan or type manually'></label>\n"
    "                <label>Password<input id='network-password' type='password' autocomplete='off' placeholder='Leave blank for open networks'></label>\n"
    "                <div class='row compact'>\n"
    "                  <button id='scan-network' type='button' class='secondary'>Scan</button>\n"
    "                  <button id='join-network' type='button'>Join</button>\n"
    "                </div>\n"
    "                <div id='network-status' class='notice muted'>Network details appear here.</div>\n"
    "                <div id='provisioning-info' class='notice muted'>Provisioning details appear here.</div>\n"
    "                <div id='network-list' class='list'></div>\n"
    "              </div>\n"
    "              <div class='list-card'>\n"
    "                <h3>Provider Auth</h3>\n"
    "                <div id='auth-status' class='notice muted'>Provider status appears here.</div>\n"
    "                <div class='notice muted'>Stored in secure device auth storage and kept across normal reflashes unless NVS is erased.</div>\n"
    "                <div class='grid-2 auth-grid'>\n"
    "                  <label>Provider<select id='auth-provider'><option value='openai_codex'>openai_codex</option><option value='openai_compat'>openai_compat</option><option value='anthropic_messages'>anthropic_messages</option></select></label>\n"
    "                  <label>Model<input id='auth-model' autocomplete='off' placeholder='gpt-5.3-codex'></label>\n"
    "                  <label>Base URL<input id='auth-base-url' autocomplete='off' placeholder='https://chatgpt.com/backend-api/codex'></label>\n"
    "                  <label>Account Id<input id='auth-account-id' autocomplete='off' placeholder='acc_...'></label>\n"
    "                </div>\n"
    "                <details class='advanced'>\n"
    "                  <summary>Advanced token fields and raw import</summary>\n"
    "                  <label>Access Token<textarea id='auth-access-token'></textarea></label>\n"
    "                  <label>Refresh Token<textarea id='auth-refresh-token' style='min-height:90px'></textarea></label>\n"
    "                  <label>Paste auth.json<textarea id='auth-import-json' style='min-height:130px' placeholder='Paste a Codex auth.json payload here, or choose a file below.'></textarea></label>\n"
    "                  <input id='auth-json-file' type='file' accept='.json,application/json' style='display:none'>\n"
    "                  <div class='row compact'>\n"
    "                    <button id='pick-auth-json' type='button' class='secondary'>Choose auth.json</button>\n"
    "                    <button id='import-auth-json' type='button' class='secondary'>Import Pasted JSON</button>\n"
    "                  </div>\n"
    "                </details>\n"
    "                <div class='row compact'>\n"
    "                  <button id='save-auth' type='button'>Save Auth</button>\n"
    "                  <button id='import-codex-cli' type='button' class='secondary'>Import Codex CLI</button>\n"
    "                  <button id='clear-auth' type='button' class='danger'>Clear</button>\n"
    "                </div>\n"
    "              </div>\n"
    "            </div>\n"
    "          </div>\n"
    "        </details>\n"
    "        <details class='card module' data-load-section='device'>\n"
    "          <summary><span>Device</span><span class='muted'>Board, workspace, and monitor</span></summary>\n"
    "          <div class='module-body'>\n"
    "            <div class='grid-2'>\n"
    "              <div class='list-card'>\n"
    "                <h3>Board Profile</h3>\n"
    "                <label>Preset<select id='board-preset'></select></label>\n"
    "                <div class='row compact'>\n"
    "                  <button id='apply-board-preset' type='button'>Apply Preset</button>\n"
    "                  <button id='refresh-board' type='button' class='secondary'>Refresh</button>\n"
    "                </div>\n"
    "                <div id='board-current' class='list'></div>\n"
    "                <details class='advanced'>\n"
    "                  <summary>Custom board descriptor</summary>\n"
    "                  <label>board.json<textarea id='board-config' style='min-height:180px'></textarea></label>\n"
    "                  <button id='save-board-config' type='button'>Save Board Config</button>\n"
    "                </details>\n"
    "              </div>\n"
    "              <div class='list-card'>\n"
    "                <h3>Workspace</h3>\n"
    "                <div id='workspace-files' class='workspace-list list'></div>\n"
    "              </div>\n"
    "            </div>\n"
    "            <div class='list-card'>\n"
    "              <div class='row compact' style='justify-content:space-between;'>\n"
    "                <h3 style='margin:0;'>System Monitor</h3>\n"
    "                <button id='refresh-monitor' type='button' class='secondary'>Refresh Monitor</button>\n"
    "              </div>\n"
    "              <div id='system-monitor' class='list'></div>\n"
    "            </div>\n"
    "            <div class='list-card'>\n"
    "              <div class='row compact' style='justify-content:space-between;'>\n"
    "                <h3 style='margin:0;'>Camera Diagnostics</h3>\n"
    "                <div class='row compact'>\n"
    "                  <button id='refresh-camera' type='button' class='secondary'>Refresh Camera</button>\n"
    "                  <button id='test-camera' type='button'>Test Capture</button>\n"
    "                </div>\n"
    "              </div>\n"
    "              <div id='camera-status' class='list'></div>\n"
    "            </div>\n"
    "            <div class='list-card'>\n"
    "              <div class='row compact' style='justify-content:space-between;'>\n"
    "                <h3 style='margin:0;'>Firmware OTA</h3>\n"
    "                <button id='refresh-ota' type='button' class='secondary'>Refresh OTA</button>\n"
    "              </div>\n"
    "              <div id='ota-status' class='notice muted'>OTA status appears here.</div>\n"
    "              <label>Firmware image<input id='ota-file' type='file' accept='.bin,application/octet-stream'></label>\n"
    "              <div class='row compact'>\n"
    "                <button id='upload-ota' type='button'>Upload and Reboot</button>\n"
    "              </div>\n"
    "              <div class='notice muted'>After the one-time serial migration to the OTA partition table, upload the built <code>espclaw_firmware.bin</code> here for future updates.</div>\n"
    "            </div>\n"
    "          </div>\n"
    "        </details>\n"
    "      </div>\n"
    "      <div id='screen-apps' class='screen'>\n"
    "        <details class='card module' open data-load-section='apps'>\n"
    "          <summary><span>Apps</span><span class='muted'>Lua bundles, source, and run actions</span></summary>\n"
    "          <div class='module-body'>\n"
    "            <div class='grid-2'>\n"
    "              <div class='list-card'>\n"
    "                <h3>Installed Apps</h3>\n"
    "                <div id='app-list' class='list'></div>\n"
    "              </div>\n"
    "              <div class='list-card editor'>\n"
    "                <h3>Selected App</h3>\n"
    "                <label>App Id<input id='app-id' name='app_id' autocomplete='off' placeholder='hello_app'></label>\n"
    "                <label>Trigger<input id='app-trigger' value='manual' autocomplete='off'></label>\n"
    "                <label>Run Payload<input id='app-payload' autocomplete='off' placeholder='payload passed to handle(trigger, payload)'></label>\n"
    "                <div class='row compact'>\n"
    "                  <button id='load-app' type='button' class='secondary'>Load</button>\n"
    "                  <button id='new-app' type='button'>Create</button>\n"
    "                  <button id='save-app' type='button'>Save Source</button>\n"
    "                  <button id='run-app' type='button' class='secondary'>Run</button>\n"
    "                  <button id='delete-app' type='button' class='danger'>Remove</button>\n"
    "                </div>\n"
    "                <div id='app-meta' class='chip-row'></div>\n"
    "                <label>Lua Source<textarea id='app-source' style='min-height:240px'></textarea></label>\n"
    "                <div id='app-result' class='notice muted'>App actions will appear here.</div>\n"
    "              </div>\n"
    "            </div>\n"
    "          </div>\n"
    "        </details>\n"
    "        <details class='card module' data-load-section='loops'>\n"
    "          <summary><span>Behaviors & Tasks</span><span class='muted'>Persisted autonomy plus live concurrent execution</span></summary>\n"
    "          <div class='module-body'>\n"
    "            <div class='grid-2'>\n"
    "              <div class='list-card'>\n"
    "                <h3>Behavior Control</h3>\n"
    "                <label>Behavior Id<input id='behavior-id' autocomplete='off' placeholder='obstacle_avoidance'></label>\n"
    "                <label>App Id<input id='behavior-app-id' autocomplete='off' placeholder='obstacle_app'></label>\n"
    "                <label>Schedule<select id='behavior-schedule'><option value='periodic'>Periodic</option><option value='event'>Event-driven</option></select></label>\n"
    "                <label>Trigger / Event<input id='behavior-trigger' value='timer' autocomplete='off'></label>\n"
    "                <label>Payload<input id='behavior-payload' autocomplete='off' placeholder='initial payload'></label>\n"
    "                <div class='grid-2'>\n"
    "                  <label>Period (ms)<input id='behavior-period' type='number' min='1' value='20'></label>\n"
    "                  <label>Iterations<input id='behavior-iterations' type='number' min='0' value='0'></label>\n"
    "                </div>\n"
    "                <label><input id='behavior-autostart' type='checkbox' style='width:auto;min-height:auto;margin-right:8px;'>Autostart on boot</label>\n"
    "                <div class='row compact'>\n"
    "                  <button id='save-behavior' type='button'>Save Behavior</button>\n"
    "                  <button id='start-behavior' type='button' class='secondary'>Start</button>\n"
    "                  <button id='stop-behavior' type='button' class='ghost'>Stop</button>\n"
    "                  <button id='delete-behavior' type='button' class='danger'>Remove</button>\n"
    "                </div>\n"
    "                <div id='behavior-result' class='notice muted'>Persist behaviors here so they can autostart and survive reboot.</div>\n"
    "              </div>\n"
    "              <div class='list-card'>\n"
    "                <h3>Task Control</h3>\n"
    "                <label>Task Id<input id='loop-id' autocomplete='off' placeholder='balance_task'></label>\n"
    "                <label>App Id<input id='loop-app-id' autocomplete='off' placeholder='balance_bot'></label>\n"
    "                <label>Schedule<select id='loop-schedule'><option value='periodic'>Periodic</option><option value='event'>Event-driven</option></select></label>\n"
    "                <label>Trigger / Event<input id='loop-trigger' value='timer' autocomplete='off'></label>\n"
    "                <label>Payload<input id='loop-payload' autocomplete='off' placeholder='step input payload'></label>\n"
    "                <div class='grid-2'>\n"
    "                  <label>Period (ms)<input id='loop-period' type='number' min='1' value='20'></label>\n"
    "                  <label>Iterations<input id='loop-iterations' type='number' min='0' value='0'></label>\n"
    "                </div>\n"
    "                <div class='row compact'>\n"
    "                  <button id='start-loop' type='button'>Start Task</button>\n"
    "                  <button id='stop-loop' type='button' class='danger'>Stop</button>\n"
    "                  <button id='refresh-loops' type='button' class='secondary'>Refresh</button>\n"
    "                </div>\n"
    "                <div id='loop-result' class='notice muted'>Task actions will appear here.</div>\n"
    "                <h3>Emit Event</h3>\n"
    "                <div class='row compact'>\n"
    "                  <input id='event-name' autocomplete='off' placeholder='sensor'>\n"
    "                  <input id='event-payload' autocomplete='off' placeholder='payload'>\n"
    "                  <button id='emit-event' type='button' class='secondary'>Emit</button>\n"
    "                </div>\n"
    "              </div>\n"
    "              <div class='list-card'>\n"
    "                <h3>Behavior Status</h3>\n"
    "                <div id='behavior-list' class='list'></div>\n"
    "              </div>\n"
    "              <div class='list-card'>\n"
    "                <h3>Task Status</h3>\n"
    "                <div id='loop-list' class='list'></div>\n"
    "              </div>\n"
    "            </div>\n"
    "          </div>\n"
    "        </details>\n"
    "      </div>\n"
    "      <div id='screen-advanced' class='screen'>\n"
    "        <details class='card module' open data-load-section='tools'>\n"
    "          <summary><span>Advanced</span><span class='muted'>Tool inventory and maintenance</span></summary>\n"
    "          <div class='module-body'>\n"
    "            <div class='list-card tool-list'>\n"
    "              <div class='row compact' style='justify-content:space-between;'>\n"
    "                <h3 style='margin:0;'>Available Tools</h3>\n"
    "                <button id='refresh-tools' type='button' class='secondary'>Refresh Tools</button>\n"
    "              </div>\n"
    "              <div id='tools-list' class='list'></div>\n"
    "            </div>\n"
    "            <div class='grid-2'>\n"
    "              <div class='list-card'>\n"
    "                <h3>Channels</h3>\n"
    "                <div id='telegram-status' class='notice muted'>Telegram config will load here.</div>\n"
    "                <label>Bot Token<input id='telegram-token' autocomplete='off' placeholder='123456:ABC...'></label>\n"
    "                <div class='grid-2'>\n"
    "                  <label>Poll Interval (s)<input id='telegram-poll-interval' type='number' min='1' value='5'></label>\n"
    "                  <label style='display:flex;align-items:center;gap:8px;margin-top:22px;'><input id='telegram-enabled' type='checkbox' checked>Telegram Enabled</label>\n"
    "                </div>\n"
    "                <div class='row compact'>\n"
    "                  <button id='save-telegram' type='button'>Save Telegram</button>\n"
    "                  <button id='clear-telegram' type='button' class='secondary'>Clear Token</button>\n"
    "                  <button id='refresh-telegram' type='button' class='secondary'>Refresh</button>\n"
    "                </div>\n"
    "              </div>\n"
    "              <div class='list-card'>\n"
    "                <h3>OTA</h3>\n"
    "                <p class='muted'>Firmware upload and signed OTA flows are staged behind the backend runtime. This surface reserves the maintenance slot without exposing unfinished actions.</p>\n"
    "                <button type='button' class='ghost'>Upload Firmware</button>\n"
    "              </div>\n"
    "            </div>\n"
    "          </div>\n"
    "        </details>\n"
    "      </div>\n"
    "    </aside>\n"
    "  </main>\n"
    "  <script>\n"
    "    const $ = (id) => document.getElementById(id);\n"
    "    const state = { loaded: new Set(), currentScreen: 'chat', currentAppId: '', chatDraft: 'Inspect the current workspace and tell me what apps are installed.' };\n"
    "    function escapeHtml(value) {\n"
    "      return String(value || '').replace(/[&<>\\\"']/g, (char) => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '\"':'&quot;', \"'\":'&#39;' }[char]));\n"
    "    }\n"
    "    function formatBytes(value) {\n"
    "      const number = Number(value || 0);\n"
    "      if (!Number.isFinite(number) || number <= 0) {\n"
    "        return '0 B';\n"
    "      }\n"
    "      const units = ['B', 'KB', 'MB', 'GB'];\n"
    "      let size = number;\n"
    "      let unitIndex = 0;\n"
    "      while (size >= 1024 && unitIndex < units.length - 1) {\n"
    "        size /= 1024;\n"
    "        unitIndex += 1;\n"
    "      }\n"
    "      return `${size >= 100 || unitIndex === 0 ? size.toFixed(0) : size.toFixed(1)} ${units[unitIndex]}`;\n"
    "    }\n"
    "    function notice(message, tone) {\n"
    "      return `<div class='notice${tone ? ` ${tone}` : ''}'>${escapeHtml(message)}</div>`;\n"
    "    }\n"
    "    function renderStats(items) {\n"
    "      return `<div class='stats'>${items.map((item) => `<div class='stat'><div class='label'>${escapeHtml(item.label)}</div><div class='value'>${escapeHtml(item.value)}</div></div>`).join('')}</div>`;\n"
    "    }\n"
    "    function setSummary(id, title, big, sub) {\n"
    "      $(id).innerHTML = `<div class='title'>${escapeHtml(title)}</div><div class='big'>${escapeHtml(big)}</div><div class='sub'>${escapeHtml(sub)}</div>`;\n"
    "    }\n"
    "    async function fetchJson(url, options) {\n"
    "      const response = await fetch(url, options);\n"
    "      const text = await response.text();\n"
    "      try { return { ok: response.ok, status: response.status, data: JSON.parse(text) }; }\n"
    "      catch (error) { return { ok: response.ok, status: response.status, data: { raw: text, parse_error: String(error) } }; }\n"
    "    }\n"
    "    function currentAppId() {\n"
    "      return $('app-id').value.trim();\n"
    "    }\n"
    "    function syncLoopAppId() {\n"
    "      if (!$('loop-app-id').value.trim()) {\n"
    "        $('loop-app-id').value = currentAppId();\n"
    "      }\n"
    "      if (!$('behavior-app-id').value.trim()) {\n"
    "        $('behavior-app-id').value = currentAppId();\n"
    "      }\n"
    "    }\n"
    "    function setScreen(name) {\n"
    "      state.currentScreen = name;\n"
    "      document.querySelectorAll('[data-screen-target]').forEach((button) => button.classList.toggle('active', button.dataset.screenTarget === name));\n"
    "      ['chat', 'setup', 'apps', 'advanced'].forEach((screenName) => {\n"
    "        const element = $(`screen-${screenName}`);\n"
    "        if (element) {\n"
    "          element.classList.toggle('active', screenName === name);\n"
    "        }\n"
    "      });\n"
    "      if (name === 'chat') {\n"
    "        ensureSectionLoaded('chat');\n"
    "      }\n"
    "    }\n"
    "    async function ensureSectionLoaded(name) {\n"
    "      if (state.loaded.has(name)) {\n"
    "        return;\n"
    "      }\n"
    "      const loaders = {\n"
    "        chat: loadChatSession,\n"
    "        connectivity: async () => { await loadNetworkStatus(); await loadProvisioningInfo(); await loadAuth(); },\n"
    "        device: async () => { await loadBoardPresets(); await loadBoardConfig(); await loadWorkspace(); await loadMonitor(); await loadCameraStatus(); await loadOtaStatus(); },\n"
    "        apps: loadApps,\n"
    "        loops: async () => { await loadBehaviors(); await loadLoops(); },\n"
    "        tools: async () => { await loadTools(); await loadTelegramConfig(); }\n"
    "      };\n"
    "      const loader = loaders[name];\n"
    "      if (!loader) {\n"
    "        return;\n"
    "      }\n"
    "      state.loaded.add(name);\n"
    "      try {\n"
    "        await loader();\n"
    "      } catch (error) {\n"
    "        state.loaded.delete(name);\n"
    "        throw error;\n"
    "      }\n"
    "    }\n"
    "    function renderOverview(status) {\n"
    "      const provisioning = status && status.provisioning ? status.provisioning : 'unknown';\n"
    "      const provider = status && status.provider ? status.provider : 'not configured';\n"
    "      const storage = status && status.storage_backend ? status.storage_backend : 'unknown';\n"
    "      const workspaceReady = status && status.workspace_ready ? 'workspace ready' : 'workspace pending';\n"
    "      $('hero-meta').innerHTML = [\n"
    "        `<span class='pill'><strong>${escapeHtml(status && status.board_profile ? status.board_profile : 'device')}</strong></span>`,\n"
    "        `<span class='pill'>${escapeHtml(storage)}</span>`,\n"
    "        `<span class='pill'>${escapeHtml(provisioning)}</span>`,\n"
    "        `<span class='pill'>${escapeHtml(provider)}</span>`,\n"
    "        `<span class='pill'>${escapeHtml(workspaceReady)}</span>`\n"
    "      ].join('');\n"
    "      setSummary('provider-summary', 'Provider', provider || 'Not configured', status && status.channel ? `channel ${status.channel}` : 'configure auth');\n"
    "      setSummary('network-summary', 'Network', provisioning, workspaceReady);\n"
    "      setSummary('board-summary', 'Board', status && status.board_profile ? status.board_profile : 'Unknown', `${storage} storage`);\n"
    "    }\n"
    "    async function loadStatus() {\n"
    "      const result = await fetchJson('/api/status');\n"
    "      const status = result.data || {};\n"
    "      renderOverview(status);\n"
    "      $('chat-yolo').checked = !!status.yolo_mode;\n"
    "    }\n"
    "    function renderBoard(board, config) {\n"
    "      if (!board || !board.configured) {\n"
    "        $('board-current').innerHTML = notice('Board descriptor is not configured yet.', 'warn');\n"
    "        return;\n"
    "      }\n"
    "      $('board-current').innerHTML = [\n"
    "        renderStats([\n"
    "          { label: 'Variant', value: board.display_name || board.variant || 'Unknown' },\n"
    "          { label: 'Source', value: board.source || 'generated' },\n"
    "          { label: 'Cores', value: String(board.task_policy && board.task_policy.cpu_cores != null ? board.task_policy.cpu_cores : '?') },\n"
    "          { label: 'Control Loop Core', value: String(board.task_policy && board.task_policy.control_loop_core != null ? board.task_policy.control_loop_core : 'auto') }\n"
    "        ]),\n"
    "        `<div class='chip-row'>${(board.pins || []).map((pin) => `<span class='chip'><strong>${escapeHtml(pin.name)}</strong> GPIO ${escapeHtml(pin.pin)}</span>`).join('')}</div>`,\n"
    "        `<div class='chip-row'>${(board.i2c || []).map((bus) => `<span class='chip'>I2C ${escapeHtml(bus.name)} ${escapeHtml(bus.sda)}/${escapeHtml(bus.scl)}</span>`).join('')}${(board.uart || []).map((uart) => `<span class='chip'>UART ${escapeHtml(uart.name)} ${escapeHtml(uart.tx)}/${escapeHtml(uart.rx)}</span>`).join('')}${(board.adc || []).map((adc) => `<span class='chip'>ADC ${escapeHtml(adc.name)} ch ${escapeHtml(adc.channel)}</span>`).join('')}</div>`\n"
    "      ].join('');\n"
    "      $('board-config').value = config && typeof config.raw_json === 'string' ? config.raw_json : '';\n"
    "      setSummary('board-summary', 'Board', board.display_name || board.variant || 'Unknown', board.source || 'generated');\n"
    "    }\n"
    "    async function loadBoardPresets() {\n"
    "      const result = await fetchJson('/api/board/presets');\n"
    "      const presets = result.data && Array.isArray(result.data.presets) ? result.data.presets : [];\n"
    "      const select = $('board-preset');\n"
    "      select.innerHTML = presets.map((preset) => `<option value='${escapeHtml(preset.variant)}'>${escapeHtml(preset.display_name)} (${escapeHtml(preset.variant)})</option>`).join('');\n"
    "      if (presets.length === 0) {\n"
    "        select.innerHTML = '<option value=\"\">No presets available</option>';\n"
    "      }\n"
    "    }\n"
    "    async function loadBoardConfig() {\n"
    "      const [boardResult, configResult] = await Promise.all([fetchJson('/api/board'), fetchJson('/api/board/config')]);\n"
    "      renderBoard(boardResult.data || {}, configResult.data || {});\n"
    "    }\n"
    "    async function applyBoardPreset() {\n"
    "      const variant = $('board-preset').value;\n"
    "      if (!variant) {\n"
    "        $('board-current').innerHTML = notice('Select a board preset first.', 'warn');\n"
    "        return;\n"
    "      }\n"
    "      const result = await fetchJson(`/api/board/apply?variant_id=${encodeURIComponent(variant)}`, { method: 'POST' });\n"
    "      $('board-current').innerHTML = notice(result.ok ? 'Board preset applied.' : 'Failed to apply board preset.', result.ok ? '' : 'warn');\n"
    "      await loadBoardConfig();\n"
    "      await loadWorkspace();\n"
    "    }\n"
    "    async function saveBoardConfig() {\n"
    "      const result = await fetchJson('/api/board/config', { method: 'PUT', headers: { 'Content-Type': 'application/json; charset=utf-8' }, body: $('board-config').value });\n"
    "      $('board-current').innerHTML = notice(result.ok ? 'Custom board descriptor saved.' : 'Failed to save board descriptor.', result.ok ? '' : 'warn');\n"
    "      await loadBoardConfig();\n"
    "      await loadWorkspace();\n"
    "    }\n"
    "    function renderNetworkStatus(status) {\n"
    "      const ssid = status && status.ssid ? status.ssid : 'not connected';\n"
    "      const transport = status && status.provisioning_transport ? status.provisioning_transport : 'idle';\n"
    "      $('network-status').innerHTML = renderStats([\n"
    "        { label: 'Connection', value: status && status.wifi_ready ? 'online' : 'offline' },\n"
    "        { label: 'SSID', value: ssid },\n"
    "        { label: 'Onboarding', value: status && status.provisioning_active ? 'active' : 'inactive' },\n"
    "        { label: 'Transport', value: transport }\n"
    "      ]);\n"
    "      setSummary('network-summary', 'Network', ssid, status && status.wifi_ready ? 'connected' : `${transport} onboarding`);\n"
    "      if (status && typeof status.ssid === 'string' && status.ssid) {\n"
    "        $('network-ssid').value = status.ssid;\n"
    "      }\n"
    "    }\n"
    "    async function loadNetworkStatus() {\n"
    "      const result = await fetchJson('/api/network/status');\n"
    "      renderNetworkStatus(result.data || {});\n"
    "    }\n"
    "    function renderProvisioningInfo(info) {\n"
    "      if (!info || !info.active) {\n"
    "        $('provisioning-info').innerHTML = notice('Provisioning is not active.', 'muted');\n"
    "        return;\n"
    "      }\n"
    "      const lines = [];\n"
    "      if (info.transport) lines.push(`<strong>Transport</strong> ${escapeHtml(info.transport)}`);\n"
    "      if (info.service_name) lines.push(`<strong>Service</strong> ${escapeHtml(info.service_name)}`);\n"
    "      if (info.pop) lines.push(`<strong>PoP</strong> ${escapeHtml(info.pop)}`);\n"
    "      if (info.admin_url) lines.push(`<strong>Admin URL</strong> <a href='${escapeHtml(info.admin_url)}'>${escapeHtml(info.admin_url)}</a>`);\n"
    "      if (info.qr_url) lines.push(`<strong>BLE Helper</strong> <a href='${escapeHtml(info.qr_url)}' target='_blank' rel='noreferrer'>Open helper</a>`);\n"
    "      $('provisioning-info').innerHTML = `<div class='list-card'>${lines.map((line) => `<div>${line}</div>`).join('')}</div>`;\n"
    "    }\n"
    "    async function loadProvisioningInfo() {\n"
    "      const result = await fetchJson('/api/network/provisioning');\n"
    "      renderProvisioningInfo(result.data || {});\n"
    "    }\n"
    "    async function scanNetworks() {\n"
    "      const result = await fetchJson('/api/network/scan');\n"
    "      const networks = result.data && Array.isArray(result.data.networks) ? result.data.networks : [];\n"
    "      const target = $('network-list');\n"
    "      if (networks.length === 0) {\n"
    "        target.innerHTML = notice('No scan results yet.', 'muted');\n"
    "        return;\n"
    "      }\n"
    "      target.innerHTML = networks.map((network) => `<div class='list-card'><div><strong>${escapeHtml(network.ssid || '<hidden>')}</strong></div><div class='muted'>${escapeHtml(network.rssi)} dBm · channel ${escapeHtml(network.channel)} · ${network.secure ? 'secured' : 'open'}</div><button type='button' class='secondary' data-ssid='${escapeHtml(network.ssid || '')}'>Use This Network</button></div>`).join('');\n"
    "      target.querySelectorAll('[data-ssid]').forEach((button) => button.addEventListener('click', () => { $('network-ssid').value = button.dataset.ssid || ''; }));\n"
    "    }\n"
    "    async function joinNetwork() {\n"
    "      const ssid = $('network-ssid').value.trim();\n"
    "      if (!ssid) {\n"
    "        $('network-status').innerHTML = notice('Enter or select an SSID first.', 'warn');\n"
    "        return;\n"
    "      }\n"
    "      const result = await fetchJson('/api/network/join', { method: 'POST', headers: { 'Content-Type': 'application/json; charset=utf-8' }, body: JSON.stringify({ ssid, password: $('network-password').value }) });\n"
    "      await loadStatus();\n"
    "      await loadNetworkStatus();\n"
    "      await loadProvisioningInfo();\n"
    "      if (result.data && result.data.message) {\n"
    "        $('network-list').innerHTML = notice(result.data.message, result.ok ? '' : 'warn');\n"
    "      }\n"
    "    }\n"
    "    function renderAuth(profile) {\n"
    "      const configured = !!(profile && profile.configured);\n"
    "      const provider = profile && profile.provider_id ? profile.provider_id : 'not configured';\n"
    "      $('auth-status').innerHTML = renderStats([\n"
    "        { label: 'State', value: configured ? 'configured' : 'missing' },\n"
    "        { label: 'Provider', value: provider },\n"
    "        { label: 'Model', value: profile && profile.model ? profile.model : 'unset' },\n"
    "        { label: 'Refresh Token', value: profile && profile.has_refresh_token ? 'present' : 'none' }\n"
    "      ]);\n"
    "      $('auth-provider').value = provider || 'openai_codex';\n"
    "      $('auth-model').value = profile && profile.model ? profile.model : '';\n"
    "      $('auth-base-url').value = profile && profile.base_url ? profile.base_url : '';\n"
    "      $('auth-account-id').value = profile && profile.account_id ? profile.account_id : '';\n"
    "      setSummary('provider-summary', 'Provider', provider || 'Not configured', configured ? `saved from ${escapeHtml(profile && profile.source ? profile.source : 'device store')}` : 'credentials missing');\n"
    "    }\n"
    "    async function loadAuth() {\n"
    "      const result = await fetchJson('/api/auth/status');\n"
    "      renderAuth(result.data || {});\n"
    "    }\n"
    "    async function refreshAuthState(message, ok) {\n"
    "      $('auth-status').innerHTML = notice(message, ok ? '' : 'warn');\n"
    "      await loadStatus();\n"
    "      await loadAuth();\n"
    "    }\n"
    "    async function saveAuth() {\n"
    "      const payload = { provider_id: $('auth-provider').value, model: $('auth-model').value.trim(), base_url: $('auth-base-url').value.trim(), account_id: $('auth-account-id').value.trim(), access_token: $('auth-access-token').value.trim(), refresh_token: $('auth-refresh-token').value.trim(), source: 'admin' };\n"
    "      const result = await fetchJson('/api/auth/codex', { method: 'PUT', headers: { 'Content-Type': 'application/json; charset=utf-8' }, body: JSON.stringify(payload) });\n"
    "      state.loaded.delete('connectivity');\n"
    "      await refreshAuthState(result.ok ? 'Provider credentials saved.' : 'Failed to save provider credentials.', result.ok);\n"
    "    }\n"
    "    async function importAuthJson(rawJson, successMessage) {\n"
    "      const payload = String(rawJson || '').trim();\n"
    "      if (!payload) {\n"
    "        $('auth-status').innerHTML = notice('Paste auth.json or choose a file first.', 'warn');\n"
    "        return;\n"
    "      }\n"
    "      const result = await fetchJson('/api/auth/import-json', { method: 'POST', headers: { 'Content-Type': 'application/json; charset=utf-8' }, body: payload });\n"
    "      if (result.ok) {\n"
    "        $('auth-import-json').value = '';\n"
    "        $('auth-json-file').value = '';\n"
    "      }\n"
    "      await refreshAuthState(result.ok ? (successMessage || 'Auth JSON imported.') : 'Failed to import auth JSON.', result.ok);\n"
    "    }\n"
    "    async function importAuthJsonFromTextarea() {\n"
    "      await importAuthJson($('auth-import-json').value, 'Auth JSON imported.');\n"
    "    }\n"
    "    function pickAuthJson() {\n"
    "      $('auth-json-file').click();\n"
    "    }\n"
    "    async function importAuthJsonFromFile(event) {\n"
    "      const file = event && event.target && event.target.files ? event.target.files[0] : null;\n"
    "      if (!file) {\n"
    "        return;\n"
    "      }\n"
    "      const rawJson = await file.text();\n"
    "      $('auth-import-json').value = rawJson;\n"
    "      await importAuthJson(rawJson, `Imported ${file.name}.`);\n"
    "    }\n"
    "    async function importCodexCli() {\n"
    "      const result = await fetchJson('/api/auth/import-codex-cli', { method: 'POST' });\n"
    "      await refreshAuthState(result.ok ? 'Codex CLI credentials imported.' : 'Failed to import Codex CLI credentials.', result.ok);\n"
    "    }\n"
    "    async function clearAuth() {\n"
    "      const result = await fetchJson('/api/auth/codex', { method: 'DELETE' });\n"
    "      $('auth-access-token').value = '';\n"
    "      $('auth-refresh-token').value = '';\n"
    "      $('auth-account-id').value = '';\n"
    "      $('auth-import-json').value = '';\n"
    "      $('auth-json-file').value = '';\n"
    "      await refreshAuthState(result.ok ? 'Provider credentials removed.' : 'Failed to clear provider credentials.', result.ok);\n"
    "    }\n"
    "    function renderTelegramConfig(config) {\n"
    "      const data = config || {};\n"
    "      $('telegram-enabled').checked = !!data.enabled;\n"
    "      $('telegram-poll-interval').value = data.poll_interval_seconds || 5;\n"
    "      $('telegram-token').value = '';\n"
    "      $('telegram-status').innerHTML = renderStats([\n"
    "        { label: 'Enabled', value: data.enabled ? 'yes' : 'no' },\n"
    "        { label: 'Configured', value: data.configured ? 'yes' : 'no' },\n"
    "        { label: 'Ready', value: data.ready ? 'yes' : 'no' },\n"
    "        { label: 'Token', value: data.token_hint || 'unset' }\n"
    "      ]);\n"
    "    }\n"
    "    async function loadTelegramConfig() {\n"
    "      const result = await fetchJson('/api/telegram/config');\n"
    "      renderTelegramConfig(result.data || {});\n"
    "    }\n"
    "    async function saveTelegramConfig(clearToken) {\n"
    "      const payload = {\n"
    "        enabled: !!$('telegram-enabled').checked,\n"
    "        poll_interval_seconds: Number.parseInt($('telegram-poll-interval').value, 10) || 5\n"
    "      };\n"
    "      const token = $('telegram-token').value.trim();\n"
    "      if (clearToken || token) {\n"
    "        payload.bot_token = clearToken ? '' : token;\n"
    "      }\n"
    "      const result = await fetchJson('/api/telegram/config', { method: 'POST', headers: { 'Content-Type': 'application/json; charset=utf-8' }, body: JSON.stringify(payload) });\n"
    "      $('telegram-status').innerHTML = notice(result.data && result.data.message ? result.data.message : (result.ok ? 'Telegram config saved.' : 'Failed to save Telegram config.'), result.ok ? '' : 'warn');\n"
    "      if (result.ok) {\n"
    "        $('telegram-token').value = '';\n"
    "      }\n"
    "      await loadTelegramConfig();\n"
    "      await loadStatus();\n"
    "    }\n"
    "    async function loadWorkspace() {\n"
    "      const result = await fetchJson('/api/workspace/files');\n"
    "      const files = result.data && Array.isArray(result.data.files) ? result.data.files : [];\n"
    "      $('workspace-files').innerHTML = files.map((file) => `<div class='list-card'><div><strong>${escapeHtml(file.path)}</strong></div><div class='${file.exists ? 'ok' : 'bad'}'>${file.exists ? 'present' : 'missing'}</div></div>`).join('') || notice('No workspace files reported.', 'muted');\n"
    "    }\n"
    "    async function loadMonitor() {\n"
    "      const result = await fetchJson('/api/monitor');\n"
    "      const monitor = result.data || {};\n"
    "      const bars = Array.isArray(monitor.cpu_load_percent) ? monitor.cpu_load_percent.map((value, index) => `<div class='bar-row'><div class='row compact'><strong>Core ${index}</strong><span class='muted'>${escapeHtml(value)}%</span></div><div class='bar-track'><div class='bar-fill' style='width:${Math.max(0, Math.min(100, Number(value || 0)))}%'></div></div></div>`).join('') : '';\n"
    "      $('system-monitor').innerHTML = [\n"
    "        renderStats([\n"
    "          { label: 'CPU', value: `${monitor.cpu_mhz || 0} MHz` },\n"
    "          { label: 'Cores', value: `${monitor.cpu_cores || 0}${monitor.dual_core ? ' dual' : ' single'}` },\n"
    "          { label: 'Memory Class', value: monitor.memory_class || 'unknown' },\n"
    "          { label: 'Firmware', value: formatBytes(monitor.app_image_size_bytes) },\n"
    "          { label: 'Flash', value: formatBytes(monitor.flash_chip_size_bytes) },\n"
    "          { label: 'Workspace', value: `${formatBytes(monitor.workspace_used_bytes)} / ${formatBytes(monitor.workspace_total_bytes)}` },\n"
    "          { label: 'RAM Free', value: `${formatBytes(monitor.ram_free_bytes)} / ${formatBytes(monitor.ram_total_bytes)}` },\n"
    "          { label: 'Min Free', value: formatBytes(monitor.ram_min_free_bytes) },\n"
    "          { label: 'Largest Block', value: formatBytes(monitor.ram_largest_free_block_bytes) },\n"
    "          { label: 'Agent Budget', value: formatBytes(monitor.agent_estimated_heap_bytes) },\n"
    "          { label: 'Target Free Heap', value: formatBytes(monitor.recommended_free_heap_bytes) },\n"
    "          { label: 'Request Buffer', value: formatBytes(monitor.agent_request_buffer_bytes) },\n"
    "          { label: 'Response Buffer', value: formatBytes(monitor.agent_response_buffer_bytes) },\n"
    "          { label: 'Codex Items', value: formatBytes(monitor.agent_codex_items_bytes) },\n"
    "          { label: 'Instructions', value: formatBytes(monitor.agent_instructions_bytes) },\n"
    "          { label: 'Tool Result Slot', value: formatBytes(monitor.agent_tool_result_bytes) },\n"
    "          { label: 'History Slots', value: `${monitor.agent_history_slots || 0}` }\n"
    "        ]),\n"
    "        bars ? `<div class='bars'>${bars}</div>` : notice('CPU load metrics are unavailable.', 'muted')\n"
    "      ].join('');\n"
    "    }\n"
    "    async function loadCameraStatus() {\n"
    "      const result = await fetchJson('/api/camera');\n"
    "      const camera = result.data || {};\n"
    "      $('camera-status').innerHTML = [\n"
    "        renderStats([\n"
    "          { label: 'Supported', value: camera.supported ? 'yes' : 'no' },\n"
    "          { label: 'Initialized', value: camera.initialized ? 'yes' : 'no' },\n"
    "          { label: 'Last Capture', value: camera.last_capture_ok ? 'ok' : 'not yet / failed' },\n"
    "          { label: 'Last File', value: camera.last_relative_path || 'n/a' },\n"
    "          { label: 'Last Image', value: camera.last_capture_ok ? `${camera.last_width || 0}x${camera.last_height || 0} · ${formatBytes(camera.last_bytes_written || 0)}` : 'n/a' }\n"
    "        ]),\n"
    "        camera.last_error ? `<div class='notice warn'>${escapeHtml(camera.last_error)}</div>` : notice(`Camera is ready. ${camera.last_relative_path ? `<a href=\"/${escapeHtml(camera.last_relative_path)}\" target=\"_blank\" rel=\"noopener\">Open last capture</a>` : 'Use Test Capture to validate the sensor and SD write path.'}`, 'muted')\n"
    "      ].join('');\n"
    "    }\n"
    "    async function testCameraCapture() {\n"
    "      $('camera-status').innerHTML = notice('Capturing a fresh test frame…', 'muted');\n"
    "      const result = await fetchJson('/api/camera/capture?filename=admin_capture.jpg', { method: 'POST' });\n"
    "      await loadCameraStatus();\n"
    "      if (result.ok && result.data && result.data.path) {\n"
    "        $('camera-status').innerHTML += notice(`Saved <a href='/${escapeHtml(result.data.path)}' target='_blank' rel='noopener'>${escapeHtml(result.data.path)}</a>`, '');\n"
    "        return;\n"
    "      }\n"
    "      $('camera-status').innerHTML += notice((result.data && result.data.error) || 'Camera capture failed.', 'warn');\n"
    "    }\n"
    "    async function loadOtaStatus() {\n"
    "      const result = await fetchJson('/api/ota/status');\n"
    "      const ota = result.data || {};\n"
    "      $('ota-status').innerHTML = [\n"
    "        renderStats([\n"
    "          { label: 'Supported', value: ota.supported ? 'yes' : 'no' },\n"
    "          { label: 'Status', value: ota.status || 'unknown' },\n"
    "          { label: 'Running', value: ota.running_partition || 'n/a' },\n"
    "          { label: 'Target', value: ota.target_partition || 'n/a' },\n"
    "          { label: 'Written', value: `${formatBytes(ota.written_bytes || 0)} / ${formatBytes(ota.expected_bytes || 0)}` }\n"
    "        ]),\n"
    "        `<div class='notice ${ota.supported ? 'muted' : 'warn'}'>${escapeHtml(ota.message || 'No OTA status available.')}</div>`\n"
    "      ].join('');\n"
    "    }\n"
    "    async function uploadOtaFirmware() {\n"
    "      const file = $('ota-file').files && $('ota-file').files[0];\n"
    "      if (!file) {\n"
    "        $('ota-status').innerHTML = notice('Choose a firmware .bin file first.', 'warn');\n"
    "        return;\n"
    "      }\n"
    "      $('ota-status').innerHTML = notice(`Uploading ${file.name} (${formatBytes(file.size)}) and scheduling reboot...`, 'muted');\n"
    "      const response = await fetch('/api/ota/upload', { method: 'POST', headers: { 'Content-Type': 'application/octet-stream' }, body: file });\n"
    "      const text = await response.text();\n"
    "      let payload = { raw: text };\n"
    "      try { payload = JSON.parse(text); } catch (error) { payload = { raw: text, parse_error: String(error) }; }\n"
    "      $('ota-status').innerHTML = notice(payload.message || (response.ok ? 'Firmware uploaded.' : 'OTA upload failed.'), response.ok ? '' : 'warn');\n"
    "      await loadOtaStatus();\n"
    "    }\n"
    "    function renderAppList(apps) {\n"
    "      $('app-list').innerHTML = apps.length === 0 ? notice('No apps installed yet.', 'muted') : apps.map((app) => `<div class='list-card'><div><strong>${escapeHtml(app.title || app.id)}</strong></div><div class='muted'>${escapeHtml(app.id)} · ${escapeHtml(app.version || '0.0.0')}</div><div class='chip-row'>${(app.permissions || []).map((permission) => `<span class='chip'>${escapeHtml(permission)}</span>`).join('')}</div><button type='button' class='secondary' data-load-app='${escapeHtml(app.id)}'>Open App</button></div>`).join('');\n"
    "      $('app-list').querySelectorAll('[data-load-app]').forEach((button) => button.addEventListener('click', () => loadApp(button.dataset.loadApp || '')));\n"
    "      setSummary('app-summary', 'Apps', apps.length === 0 ? 'None' : `${apps.length} installed`, apps.length === 0 ? 'create one in Apps' : 'ready to edit');\n"
    "    }\n"
    "    async function loadApps() {\n"
    "      const result = await fetchJson('/api/apps');\n"
    "      const apps = result.data && Array.isArray(result.data.apps) ? result.data.apps : [];\n"
    "      renderAppList(apps);\n"
    "    }\n"
    "    function renderAppDetail(app) {\n"
    "      if (!app) {\n"
    "        $('app-meta').innerHTML = '';\n"
    "        return;\n"
    "      }\n"
    "      $('app-meta').innerHTML = [`<span class='chip'><strong>${escapeHtml(app.id)}</strong></span>`, `<span class='chip'>${escapeHtml(app.version || '0.0.0')}</span>`, ...(app.triggers || []).map((trigger) => `<span class='chip'>${escapeHtml(trigger)}</span>`), ...(app.permissions || []).map((permission) => `<span class='chip'>${escapeHtml(permission)}</span>`)].join('');\n"
    "      $('app-source').value = app.source || '';\n"
    "      state.currentAppId = app.id || '';\n"
    "    }\n"
    "    async function loadApp(appId) {\n"
    "      if (!appId) {\n"
    "        $('app-result').innerHTML = notice('Enter an app id first.', 'warn');\n"
    "        return;\n"
    "      }\n"
    "      $('app-id').value = appId;\n"
    "      $('loop-app-id').value = appId;\n"
    "      const result = await fetchJson(`/api/apps/detail?app_id=${encodeURIComponent(appId)}`);\n"
    "      if (result.data && result.data.app) {\n"
    "        renderAppDetail(result.data.app);\n"
    "        $('app-result').innerHTML = notice(`Loaded ${appId}.`, '');\n"
    "      } else {\n"
    "        $('app-result').innerHTML = notice('App could not be loaded.', 'warn');\n"
    "      }\n"
    "    }\n"
    "    async function createApp() {\n"
    "      const appId = currentAppId();\n"
    "      if (!appId) {\n"
    "        $('app-result').innerHTML = notice('Enter an app id first.', 'warn');\n"
    "        return;\n"
    "      }\n"
    "      const result = await fetchJson(`/api/apps/scaffold?app_id=${encodeURIComponent(appId)}`, { method: 'POST' });\n"
    "      $('app-result').innerHTML = notice(result.ok ? `Created ${appId}.` : `Failed to create ${appId}.`, result.ok ? '' : 'warn');\n"
    "      await loadApps();\n"
    "      await loadApp(appId);\n"
    "    }\n"
    "    async function saveApp() {\n"
    "      const appId = currentAppId();\n"
    "      if (!appId) {\n"
    "        $('app-result').innerHTML = notice('Enter an app id first.', 'warn');\n"
    "        return;\n"
    "      }\n"
    "      const result = await fetchJson(`/api/apps/source?app_id=${encodeURIComponent(appId)}`, { method: 'PUT', headers: { 'Content-Type': 'text/plain; charset=utf-8' }, body: $('app-source').value });\n"
    "      $('app-result').innerHTML = notice(result.ok ? 'Source saved.' : 'Failed to save source.', result.ok ? '' : 'warn');\n"
    "      await loadApps();\n"
    "    }\n"
    "    async function runApp() {\n"
    "      const appId = currentAppId();\n"
    "      if (!appId) {\n"
    "        $('app-result').innerHTML = notice('Enter an app id first.', 'warn');\n"
    "        return;\n"
    "      }\n"
    "      const trigger = $('app-trigger').value.trim() || 'manual';\n"
    "      const result = await fetchJson(`/api/apps/run?app_id=${encodeURIComponent(appId)}&trigger=${encodeURIComponent(trigger)}`, { method: 'POST', headers: { 'Content-Type': 'text/plain; charset=utf-8' }, body: $('app-payload').value });\n"
    "      $('app-result').innerHTML = notice(result.ok ? 'App executed successfully.' : 'App execution failed.', result.ok ? '' : 'warn') + (result.data && result.data.message ? `<div class='muted' style='margin-top:8px;'>${escapeHtml(result.data.message)}</div>` : '');\n"
    "    }\n"
    "    async function deleteApp() {\n"
    "      const appId = currentAppId();\n"
    "      if (!appId) {\n"
    "        $('app-result').innerHTML = notice('Enter an app id first.', 'warn');\n"
    "        return;\n"
    "      }\n"
    "      const result = await fetchJson(`/api/apps?app_id=${encodeURIComponent(appId)}`, { method: 'DELETE' });\n"
    "      $('app-result').innerHTML = notice(result.ok ? `Removed ${appId}.` : `Failed to remove ${appId}.`, result.ok ? '' : 'warn');\n"
    "      $('app-source').value = '';\n"
    "      $('app-meta').innerHTML = '';\n"
    "      await loadApps();\n"
    "    }\n"
    "    async function loadBehaviors() {\n"
    "      const result = await fetchJson('/api/behaviors');\n"
    "      const behaviors = result.data && Array.isArray(result.data.behaviors) ? result.data.behaviors : [];\n"
    "      $('behavior-list').innerHTML = behaviors.length === 0 ? notice('No persisted behaviors yet.', 'muted') : behaviors.map((behavior) => `<div class='list-card'><div><strong>${escapeHtml(behavior.behavior_id || 'behavior')}</strong></div><div class='muted'>${escapeHtml(behavior.app_id || '')} · ${escapeHtml(behavior.schedule || 'periodic')} · ${escapeHtml(behavior.trigger || '')}</div><div class='chip-row'><span class='chip'>${behavior.autostart ? 'autostart' : 'manual start'}</span><span class='chip'>${behavior.active ? 'running' : (behavior.completed ? 'completed' : 'idle')}</span>${behavior.stop_requested ? \"<span class='chip'>stop requested</span>\" : ''}</div>${behavior.last_result ? `<div class='muted'>${escapeHtml(behavior.last_result)}</div>` : ''}<button type='button' class='secondary' data-load-behavior='${escapeHtml(behavior.behavior_id || '')}'>Use Behavior</button></div>`).join('');\n"
    "      $('behavior-list').querySelectorAll('[data-load-behavior]').forEach((button) => button.addEventListener('click', () => {\n"
    "        const card = behaviors.find((behavior) => behavior.behavior_id === (button.dataset.loadBehavior || ''));\n"
    "        if (!card) { return; }\n"
    "        $('behavior-id').value = card.behavior_id || '';\n"
    "        $('behavior-app-id').value = card.app_id || '';\n"
    "        $('behavior-schedule').value = card.schedule || 'periodic';\n"
    "        $('behavior-trigger').value = card.trigger || 'timer';\n"
    "        $('behavior-payload').value = card.payload || '';\n"
    "        $('behavior-period').value = card.period_ms || 20;\n"
    "        $('behavior-iterations').value = card.max_iterations || 0;\n"
    "        $('behavior-autostart').checked = !!card.autostart;\n"
    "      }));\n"
    "    }\n"
    "    async function saveBehavior() {\n"
    "      const behaviorId = $('behavior-id').value.trim();\n"
    "      const appId = $('behavior-app-id').value.trim() || currentAppId();\n"
    "      if (!behaviorId || !appId) {\n"
    "        $('behavior-result').innerHTML = notice('Enter both behavior id and app id first.', 'warn');\n"
    "        return;\n"
    "      }\n"
    "      const schedule = $('behavior-schedule').value || 'periodic';\n"
    "      const trigger = $('behavior-trigger').value.trim() || (schedule === 'event' ? 'sensor' : 'timer');\n"
    "      const periodMs = Number.parseInt($('behavior-period').value, 10) || 20;\n"
    "      const iterations = Number.parseInt($('behavior-iterations').value, 10) || 0;\n"
    "      const autostart = $('behavior-autostart').checked ? 1 : 0;\n"
    "      const query = `/api/behaviors/register?behavior_id=${encodeURIComponent(behaviorId)}&app_id=${encodeURIComponent(appId)}&schedule=${encodeURIComponent(schedule)}&trigger=${encodeURIComponent(trigger)}&period_ms=${encodeURIComponent(periodMs)}&iterations=${encodeURIComponent(iterations)}&autostart=${encodeURIComponent(autostart)}`;\n"
    "      const result = await fetchJson(query, { method: 'POST', headers: { 'Content-Type': 'text/plain; charset=utf-8' }, body: $('behavior-payload').value });\n"
    "      $('behavior-result').innerHTML = notice(result.ok ? 'Behavior saved.' : 'Failed to save behavior.', result.ok ? '' : 'warn');\n"
    "      await loadBehaviors();\n"
    "    }\n"
    "    async function startBehavior() {\n"
    "      const behaviorId = $('behavior-id').value.trim();\n"
    "      if (!behaviorId) {\n"
    "        $('behavior-result').innerHTML = notice('Enter a behavior id first.', 'warn');\n"
    "        return;\n"
    "      }\n"
    "      const result = await fetchJson(`/api/behaviors/start?behavior_id=${encodeURIComponent(behaviorId)}`, { method: 'POST' });\n"
    "      $('behavior-result').innerHTML = notice(result.ok ? 'Behavior started.' : 'Failed to start behavior.', result.ok ? '' : 'warn');\n"
    "      await loadBehaviors();\n"
    "      await loadLoops();\n"
    "    }\n"
    "    async function stopBehavior() {\n"
    "      const behaviorId = $('behavior-id').value.trim();\n"
    "      if (!behaviorId) {\n"
    "        $('behavior-result').innerHTML = notice('Enter a behavior id first.', 'warn');\n"
    "        return;\n"
    "      }\n"
    "      const result = await fetchJson(`/api/behaviors/stop?behavior_id=${encodeURIComponent(behaviorId)}`, { method: 'POST' });\n"
    "      $('behavior-result').innerHTML = notice(result.ok ? 'Behavior stop requested.' : 'Failed to stop behavior.', result.ok ? '' : 'warn');\n"
    "      await loadBehaviors();\n"
    "      await loadLoops();\n"
    "    }\n"
    "    async function deleteBehavior() {\n"
    "      const behaviorId = $('behavior-id').value.trim();\n"
    "      if (!behaviorId) {\n"
    "        $('behavior-result').innerHTML = notice('Enter a behavior id first.', 'warn');\n"
    "        return;\n"
    "      }\n"
    "      const result = await fetchJson(`/api/behaviors?behavior_id=${encodeURIComponent(behaviorId)}`, { method: 'DELETE' });\n"
    "      $('behavior-result').innerHTML = notice(result.ok ? 'Behavior removed.' : 'Failed to remove behavior.', result.ok ? '' : 'warn');\n"
    "      await loadBehaviors();\n"
    "      await loadLoops();\n"
    "    }\n"
    "    async function loadLoops() {\n"
    "      const result = await fetchJson('/api/tasks');\n"
    "      const loops = result.data && Array.isArray(result.data.tasks) ? result.data.tasks : [];\n"
    "      $('loop-list').innerHTML = loops.length === 0 ? notice('No tasks are running.', 'muted') : loops.map((loop) => `<div class='list-card'><div><strong>${escapeHtml(loop.task_id || 'task')}</strong></div><div class='muted'>${escapeHtml(loop.app_id || '')} · ${escapeHtml(loop.trigger || '')} · ${escapeHtml(loop.schedule || 'periodic')}</div><div class='chip-row'><span class='chip'>${escapeHtml(loop.completed ? 'completed' : 'active')}</span><span class='chip'>${escapeHtml(loop.iterations_completed || 0)} iterations</span>${loop.stop_requested ? \"<span class='chip'>stop requested</span>\" : ''}</div>${loop.last_result ? `<div class='muted'>${escapeHtml(loop.last_result)}</div>` : ''}</div>`).join('');\n"
    "    }\n"
    "    async function startLoop() {\n"
    "      const loopId = $('loop-id').value.trim();\n"
    "      const appId = $('loop-app-id').value.trim() || currentAppId();\n"
    "      if (!loopId || !appId) {\n"
    "        $('loop-result').innerHTML = notice('Enter both task id and app id first.', 'warn');\n"
    "        return;\n"
    "      }\n"
    "      const schedule = $('loop-schedule').value || 'periodic';\n"
    "      const trigger = $('loop-trigger').value.trim() || (schedule === 'event' ? 'sensor' : 'timer');\n"
    "      const periodMs = Number.parseInt($('loop-period').value, 10) || 20;\n"
    "      const iterations = Number.parseInt($('loop-iterations').value, 10) || 0;\n"
    "      const query = `/api/tasks/start?task_id=${encodeURIComponent(loopId)}&app_id=${encodeURIComponent(appId)}&schedule=${encodeURIComponent(schedule)}&trigger=${encodeURIComponent(trigger)}&period_ms=${encodeURIComponent(periodMs)}&iterations=${encodeURIComponent(iterations)}`;\n"
    "      const result = await fetchJson(query, { method: 'POST', headers: { 'Content-Type': 'text/plain; charset=utf-8' }, body: $('loop-payload').value });\n"
    "      $('loop-result').innerHTML = notice(result.ok ? 'Task started.' : 'Failed to start task.', result.ok ? '' : 'warn');\n"
    "      await loadLoops();\n"
    "    }\n"
    "    async function stopLoop() {\n"
    "      const loopId = $('loop-id').value.trim();\n"
    "      if (!loopId) {\n"
    "        $('loop-result').innerHTML = notice('Enter a task id first.', 'warn');\n"
    "        return;\n"
    "      }\n"
    "      const result = await fetchJson(`/api/tasks/stop?task_id=${encodeURIComponent(loopId)}`, { method: 'POST' });\n"
    "      $('loop-result').innerHTML = notice(result.ok ? 'Task stop requested.' : 'Failed to stop task.', result.ok ? '' : 'warn');\n"
    "      await loadLoops();\n"
    "    }\n"
    "    async function emitEvent() {\n"
    "      const name = $('event-name').value.trim() || $('loop-trigger').value.trim();\n"
    "      if (!name) {\n"
    "        $('loop-result').innerHTML = notice('Enter an event name first.', 'warn');\n"
    "        return;\n"
    "      }\n"
    "      const result = await fetchJson(`/api/events/emit?name=${encodeURIComponent(name)}`, { method: 'POST', headers: { 'Content-Type': 'text/plain; charset=utf-8' }, body: $('event-payload').value });\n"
    "      $('loop-result').innerHTML = notice(result.ok ? 'Event emitted.' : 'Failed to emit event.', result.ok ? '' : 'warn');\n"
    "      await loadLoops();\n"
    "    }\n"
    "    async function loadTools() {\n"
    "      const result = await fetchJson('/api/tools');\n"
    "      const tools = result.data && Array.isArray(result.data.tools) ? result.data.tools : [];\n"
    "      $('tools-list').innerHTML = tools.length === 0 ? notice('No tools registered.', 'muted') : tools.map((tool) => `<div class='list-card'><div><strong>${escapeHtml(tool.name)}</strong></div><div class='muted'>${escapeHtml(tool.summary || '')}</div><div class='chip-row'><span class='chip'>${escapeHtml(tool.safety || 'read_only')}</span></div></div>`).join('');\n"
    "    }\n"
    "    function parseTranscript(transcript) {\n"
    "      return String(transcript || '').split('\\n').map((line) => line.trim()).filter(Boolean).map((line) => { try { return JSON.parse(line); } catch (error) { return { role: 'tool', content: line }; } });\n"
    "    }\n"
    "    function renderTranscript(entries) {\n"
    "      const target = $('chat-transcript');\n"
    "      if (!entries.length) {\n"
    "        target.innerHTML = \"<div class='empty-state'>No transcript yet. Send a message to start a run.</div>\";\n"
    "        return;\n"
    "      }\n"
    "      target.innerHTML = entries.map((entry) => {\n"
    "        const role = entry && entry.role ? entry.role : 'tool';\n"
    "        const content = entry && entry.content ? entry.content : '';\n"
    "        return `<div class='bubble ${escapeHtml(role)}'><div class='role'>${escapeHtml(role)}</div><pre>${escapeHtml(content)}</pre></div>`;\n"
    "      }).join('');\n"
    "      target.scrollTop = target.scrollHeight;\n"
    "    }\n"
    "    async function loadChatSession() {\n"
    "      const sessionId = $('chat-session-id').value.trim() || 'admin';\n"
    "      const result = await fetchJson(`/api/chat/session?session_id=${encodeURIComponent(sessionId)}`);\n"
    "      renderTranscript(parseTranscript(result.data && result.data.transcript ? result.data.transcript : ''));\n"
    "    }\n"
    "    async function runChat() {\n"
    "      const sessionId = $('chat-session-id').value.trim() || 'admin';\n"
    "      const message = $('chat-input').value.trim();\n"
    "      if (!message) {\n"
    "        $('chat-result').className = 'notice warn';\n"
    "        $('chat-result').textContent = 'Enter a chat message first.';\n"
    "        return;\n"
    "      }\n"
    "      $('chat-result').className = 'notice muted';\n"
    "      $('chat-result').textContent = 'Running model loop…';\n"
    "      const yolo = $('chat-yolo').checked;\n"
    "      const result = await fetchJson(`/api/chat/run?session_id=${encodeURIComponent(sessionId)}${yolo ? '&yolo=1' : ''}`, { method: 'POST', headers: { 'Content-Type': 'text/plain; charset=utf-8' }, body: message });\n"
    "      $('chat-result').className = `notice${result.ok ? '' : ' warn'}`;\n"
    "      $('chat-result').textContent = result.data && result.data.final_text ? result.data.final_text : (result.ok ? (yolo ? 'YOLO run completed.' : 'Run completed.') : 'Run failed.');\n"
    "      await loadChatSession();\n"
    "    }\n"
    "    function bindUi() {\n"
    "      $('chat-input').value = state.chatDraft;\n"
    "      document.querySelectorAll('[data-screen-target]').forEach((button) => button.addEventListener('click', () => setScreen(button.dataset.screenTarget || 'chat')));\n"
    "      document.querySelectorAll('details[data-load-section]').forEach((detail) => detail.addEventListener('toggle', () => { if (detail.open) { ensureSectionLoaded(detail.dataset.loadSection || ''); } }));\n"
    "      $('load-session').addEventListener('click', loadChatSession);\n"
    "      $('run-chat').addEventListener('click', runChat);\n"
    "      $('clear-chat-draft').addEventListener('click', () => { $('chat-input').value = ''; });\n"
    "      $('refresh-board').addEventListener('click', loadBoardConfig);\n"
    "      $('apply-board-preset').addEventListener('click', applyBoardPreset);\n"
    "      $('save-board-config').addEventListener('click', saveBoardConfig);\n"
    "      $('scan-network').addEventListener('click', scanNetworks);\n"
    "      $('join-network').addEventListener('click', joinNetwork);\n"
    "      $('save-auth').addEventListener('click', saveAuth);\n"
    "      $('pick-auth-json').addEventListener('click', pickAuthJson);\n"
    "      $('import-auth-json').addEventListener('click', importAuthJsonFromTextarea);\n"
    "      $('auth-json-file').addEventListener('change', importAuthJsonFromFile);\n"
    "      $('import-codex-cli').addEventListener('click', importCodexCli);\n"
    "      $('clear-auth').addEventListener('click', clearAuth);\n"
    "      $('save-telegram').addEventListener('click', () => saveTelegramConfig(false));\n"
    "      $('clear-telegram').addEventListener('click', () => saveTelegramConfig(true));\n"
    "      $('refresh-telegram').addEventListener('click', loadTelegramConfig);\n"
    "      $('refresh-monitor').addEventListener('click', loadMonitor);\n"
    "      $('refresh-camera').addEventListener('click', loadCameraStatus);\n"
    "      $('test-camera').addEventListener('click', testCameraCapture);\n"
    "      $('refresh-ota').addEventListener('click', loadOtaStatus);\n"
    "      $('upload-ota').addEventListener('click', uploadOtaFirmware);\n"
    "      $('new-app').addEventListener('click', createApp);\n"
    "      $('load-app').addEventListener('click', () => loadApp(currentAppId()));\n"
    "      $('save-app').addEventListener('click', saveApp);\n"
    "      $('run-app').addEventListener('click', runApp);\n"
    "      $('delete-app').addEventListener('click', deleteApp);\n"
    "      $('save-behavior').addEventListener('click', saveBehavior);\n"
    "      $('start-behavior').addEventListener('click', startBehavior);\n"
    "      $('stop-behavior').addEventListener('click', stopBehavior);\n"
    "      $('delete-behavior').addEventListener('click', deleteBehavior);\n"
    "      $('start-loop').addEventListener('click', startLoop);\n"
    "      $('stop-loop').addEventListener('click', stopLoop);\n"
    "      $('emit-event').addEventListener('click', emitEvent);\n"
    "      $('refresh-loops').addEventListener('click', async () => { await loadBehaviors(); await loadLoops(); });\n"
    "      $('loop-schedule').addEventListener('change', () => { const eventMode = $('loop-schedule').value === 'event'; $('loop-trigger').value = eventMode ? 'sensor' : 'timer'; $('loop-period').disabled = eventMode; });\n"
    "      $('behavior-schedule').addEventListener('change', () => { const eventMode = $('behavior-schedule').value === 'event'; $('behavior-trigger').value = eventMode ? 'sensor' : 'timer'; $('behavior-period').disabled = eventMode; });\n"
    "      $('refresh-tools').addEventListener('click', loadTools);\n"
    "      $('app-id').addEventListener('change', syncLoopAppId);\n"
    "    }\n"
    "    bindUi();\n"
    "    loadStatus();\n"
    "    setScreen('chat');\n"
    "  </script>\n"
    "</body>\n"
    "</html>\n";

const char *espclaw_admin_ui_html(void)
{
    return ESPCLAW_ADMIN_UI;
}

size_t espclaw_admin_ui_length(void)
{
    return strlen(ESPCLAW_ADMIN_UI);
}
